---
hosts:
  - name: 192.168.100.141
    username: admin
    password: cisco
    port: 22
    cmd: "show running-config"
    type: cisco_xe
  - name: 192.168.100.142
    username: admin
    password: cisco
    port: 22
    cmd: "show running-config"
    type: cisco_xe
